---@class HRLibConfig
---@field defaultWebHook string
---@field defaultNotificationsPosition string
---@field alertDialogueTranslation { agreeButton: string, cancelButton: string }
---@field inputDialogueTranslation { confirmButton: string, cancelButton: string }

---@class HRLibClientFPlayer
---@field Teleport fun(self: HRLibClientFPlayer, coords: vector3)
---@field SpawnVehicle fun(self: HRLibClientFPlayer, vehModel: string|integer, spawnPedInside: boolean?, saveVehicle: boolean?): integer?
---@field Freeze fun(self: HRLibClientFPlayer, toggle: boolean)

---@class HRLibServerFPlayer
---@field Teleport fun(self: HRLibServerFPlayer, coords: vector3)
---@field SpawnVehicle fun(self: HRLibServerFPlayer, vehModel: string|integer, spawnPlayerInside: boolean?, saveVehicle: boolean?): integer?
---@field Notify fun(self: HRLibServerFPlayer, description: string?, type: 'success'|'info'|'error'|'warning'?, duration: number?, pos: 'top-right'|'center-right'|'bottom-right'|'frombelow-right'|'top-left'|'left-center'|'frombelow-left'?, sound: boolean?)
---@field FocusedEvent fun(self: HRLibServerFPlayer, eventName: string, ...: any)

---@class HRLibClientIPlayer
---@field source integer
---@field id integer
---@field Id integer
---@field ID integer
---@field playerId integer
---@field player integer
---@field serverId integer
---@field plId integer
---@field serverPlId integer
---@field sPlId integer
---@field state table?
---@field invincible_2 boolean
---@field max { stamina: number, armour: integer, health: integer }
---@field currStamina number
---@field veh { dmgModifier: number, defModifier: number }
---@field weapon { dmgModifier: number, defModifier: number, defModifier_2: number, malee: { dmgModifier: number, defModifier: number } }
---@field coords vector3
---@field heading number
---@field currStealthNoise number
---@field group integer
---@field invincible boolean
---@field name string
---@field ped integer
---@field pedIsFollowing integer
---@field rgbColor integer
---@field team integer
---@field underWaterTimeRmng number
---@field entity { targetEntity: { [1]: boolean, [2]: integer }, health: number, archeTypeName: string, attachedTo: integer, model: integer, mapDataOwner: { [1]: boolean, [2]: integer, [3]: integer }, alpha: integer, forward: { vector: vector3, x: number, y: number }, heightAboveGround: number, lodDist: integer, matrix: vector3[], pitch: number, populationType: integer, quaternion: number[], roll: number, rotationVelocity: vector3, speed: number, submergedLvl: number, type: number, uprightValue: number, velocity: vector3, lastHitMaterial: integer, nearestPl: integer, objectIndex: integer, vehIndex: integer, hasLoadedCollisionAround: boolean, hasBeenDamagedByAnyObject: boolean, hasBeenDamagedByAnyVeh: boolean, hasCollidedWithAnything: boolean, isAttached: boolean, isAttachedToAnyObject: boolean, isAttachedToAnyPed: boolean, isAttachedToAnyVeh: boolean, isDead: boolean, isInAir: boolean, isInWater: boolean, isOccluded: boolean, isOnScreen: boolean, isStatic: boolean, isUpsideDown: boolean, isVisible: boolean, isVisibleToScript: boolean, isWaitingForWorldCollision: boolean, isFreezed: boolean }
---@field streetName string

---@class HRLibServerIPlayer
---@field source integer
---@field id integer
---@field Id integer
---@field ID integer
---@field playerId integer
---@field player integer
---@field serverId integer
---@field plId integer
---@field serverPlId integer
---@field sPlId integer
---@field state table?
---@field name string
---@field identifier { license: string, license2: string, steam: string, discord: string, xbl: string, live: string, ip: string, fivem: string }
---@field identifiersNum integer
---@field ping integer
---@field max { health: integer, armour: integer }
---@field ped integer
---@field tokens { t1: string, t2: string, t3: string, t4: string, allString: string, num: integer }
---@field camRotation vector3
---@field endPoint string
---@field fakeWantedLvl integer
---@field guid string
---@field invincible boolean
---@field lastMsg integer
---@field rountingBucket integer
---@field team integer
---@field wanted { centrePos: vector3, lvl: integer }
---@field weapon { dmgModifier: number, defModifier: number, defModifier_2: number, maleeWeaponDmgModifier: number }
---@field coords vector3
---@field heading number
---@field health integer
---@field entity { attachedTo: integer, isFreezed: boolean, model: integer, populationType: integer, rotation: vector3, rotationVelocity: vector3, rountingBucket: integer, script: string, speed: number, type: integer, velocity: vector3, sourceOfDamage: integer, sourceOfDeath: integer, isVisible: boolean, netId: integer }
---@field veh { bodyHealth: number, colours: integer[], custom: { primaryColour: integer[], secondaryColour: integer[] }, dashboardColour: integer, dirtLevel: number, doorLockStatus: number, doorStatus: integer, doorsLockedForPlayer: integer, engineHealth: number, extraColours: integer[], flightNozzlePosition: number, handbrake: boolean, headlightsColour: integer, homingLockonState: integer, interiorColour: integer, lightsState: boolean[], livery: integer, lockOnTarget: { [1]: boolean, [2]: integer }, plate: string, plateIndex: integer, petrolTankHealth: number, radioStationIndex: integer, roofLivery: integer, steeringAngle: number, type: string, tyreSmokeColour: integer[], wheelType: integer, windowTint: integer }
---@field vehicle integer

---@class HRLibCloseIPlayer : HRLibClientIPlayer
---@field distance number

---@class HRLibCloseFPlayer : HRLibClientFPlayer
---@field distance number

---@class HRLibBlipOptions
---@field sprite integer?
---@field colour integer?
---@field scale number?
---@field alpha number?
---@field asShortRange boolean?
---@field category integer?
---@field displayId integer?
---@field flashBlip boolean?
---@field flashInterval number?

---@class HRLibBlipForCoordOptions
---@field coords vector3

---@class HRLibBlipForEntityOptions
---@field entity integer

---@class HRLibBlipForAreaOptions
---@field coords vector3
---@field width number
---@field height number

---@class HRLibBlipForPickupOptions
---@field pickup integer

---@class HRLibTableFunctions
---@field focusedArray fun(array: table[], focus: table, cb: fun(i: integer, curr: table))
---@field focusedHash fun(hash: table, focus: table|any, cb: fun(key: string, value: any[], arrayInfo: { i: integer, curr: table }))
---@field getHashLength fun(hash: table): integer
---@field find fun(tbl: any[], value: any|any[], returnIndex: boolean?, isValueKey: boolean?): boolean
---@field deepclone fun(tbl: table): table

---@class HRLibServerBridge
---@field getName fun(playerId: integer, nameType: 'firstname'|'lastname'?): string
---@field getJob fun(playerId: integer, returnGrade: boolean?): string, integer?
---@field getMoney fun(playerId: integer, account: 'cash'|'bank'): integer?
---@field setJob fun(playerId: integer, jobName: string, jobGrade: integer)
---@field setMoney fun(playerId: integer, account: 'cash'|'bank', amount: integer)

---@class HRLibInputDialogueTextOptions
---@field label string
---@field placeholder string?

---@class HRLibVehicleProperties
---@field model number?
---@field plate string?
---@field plateIndex number?
---@field bodyHealth number?
---@field engineHealth number?
---@field tankHealth number?
---@field fuelLevel number?
---@field oilLevel number?
---@field dirtLevel number?
---@field paintType1 number?
---@field paintType2 number?
---@field color1 number|number[]?
---@field color2 number|number[]?
---@field pearlescentColor number?
---@field interiorColor number?
---@field dashboardColor number?
---@field wheelColor number?
---@field wheelWidth number?
---@field wheelSize number?
---@field wheels number?
---@field windowTint number?
---@field xenonColor number?
---@field neonEnabled boolean[]?
---@field neonColor number | number[]?
---@field extras table<number|string,0|1>?
---@field tyreSmokeColor number | number[]?
---@field modSpoilers number?
---@field modFrontBumper number?
---@field modRearBumper number?
---@field modSideSkirt number?
---@field modExhaust number?
---@field modFrame number?
---@field modGrille number?
---@field modHood number?
---@field modFender number?
---@field modRightFender number?
---@field modRoof number?
---@field modEngine number?
---@field modBrakes number?
---@field modTransmission number?
---@field modHorns number?
---@field modSuspension number?
---@field modArmor number?
---@field modNitrous number?
---@field modTurbo boolean?
---@field modSubwoofer boolean?
---@field modSmokeEnabled boolean?
---@field modHydraulics boolean?
---@field modXenon boolean?
---@field modFrontWheels number?
---@field modBackWheels number?
---@field modCustomTiresF boolean?
---@field modCustomTiresR boolean?
---@field modPlateHolder number?
---@field modVanityPlate number?
---@field modTrimA number?
---@field modOrnaments number?
---@field modDashboard number?
---@field modDial number?
---@field modDoorSpeaker number?
---@field modSeats number?
---@field modSteeringWheel number?
---@field modShifterLeavers number?
---@field modAPlate number?
---@field modSpeakers number?
---@field modTrunk number?
---@field modHydrolic number?
---@field modEngineBlock number?
---@field modAirFilter number?
---@field modStruts number?
---@field modArchCover number?
---@field modAerials number?
---@field modTrimB number?
---@field modTank number?
---@field modWindows number?
---@field modDoorR number?
---@field modLivery number?
---@field modRoofLivery number?
---@field modLightbar number?
---@field livery number?
---@field windows number[]?
---@field doors number[]?
---@field tyres table<number|string,1|2>?
---@field bulletProofTyres boolean?
---@field driftTyres boolean?