name: Revert Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "GitHub Actions"

      - name: Rollback Last Commit
        run: |
          git checkout main
          git reset --hard HEAD~1  # Връща последния комит
          git push origin main --force  # Принудително качва промените в main
