name: Revert Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  revert-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --local user.email "hr.fivem.dev@gmail.com"
          git config --local user.name "GitHub Actions"

      - name: Revert Latest Commit
        run: |
          git revert HEAD --no-edit

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/HRScripts/HRLib.git main
