name: Revert Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  revert-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure we have the full history

      - name: Set up Git
        run: |
          git config --local user.email "hr.fivem.dev@gmail.com"
          git config --local user.name "GitHub Actions"

      - name: Revert Latest Commit
        run: |
          git revert HEAD --no-edit || echo "No changes to revert."

      - name: Remove Workflow Directory Changes
        run: |
          git reset HEAD .github/workflows  # Unstage any changes in workflows directory
          git checkout -- .github/workflows  # Restore the workflows directory to its previous state

      - name: Push Changes to Main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/HRScripts/HRLib.git main
