name: Revert Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  revert-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "hr.fivem.dev@gmail.com"
          git config --local user.name "GitHub Actions"

      - name: Check Current Branch
        run: |
          git branch
          git log --oneline -n 5

      - name: Revert to Previous Commit
        run: |
          git checkout main
          git fetch origin
          git reset --hard HEAD~1
          git push origin main --force
