name: Revert Commit

on:
  workflow_dispatch:

permissions:
  contents: write
  workflows: write

jobs:
  revert-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --local user.email "hr.fivem.dev@gmail.com"
          git config --local user.name "GitHub Actions"

      - name: Check Current Branch
        run: |
          git branch
          git log --oneline -n 5  # Show the last 5 commits for debugging

      - name: Revert to Previous Commit
        run: |
          git checkout main
          git reset --hard HEAD~1  # Use HEAD~1 directly
          git push origin main --force
