name: Revert Commit

on:
  workflow_dispatch:

permissions:
  contents: write  # Allow modifying repository contents

jobs:
  revert-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for the repository

      - name: Set up Git
        run: |
          git config --local user.email "hr.fivem.dev@gmail.com"
          git config --local user.name "GitHub Actions"

      - name: Check Current Branch
        run: |
          git branch
          git log --oneline -n 5

      - name: Revert to Previous Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
        run: |
          git checkout main
          git reset --hard HEAD~1
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/HRScripts/HRLib.git main --force
